
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/utils/auth";
import Providar from "@/app/Providar"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Intervuo",
  description: "Generated by pathfinder",
};

export default function RootLayout({ children }) {
  return (
    <Providar>
      <AuthProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </html>
      </AuthProvider>
    </Providar>
  );
}